name: Cancel
on:
  workflow_run:
    workflows: ['automerge', 'build', 'codeql-analysis']
    types:
      - requested
permissions:
  actions: write
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@850af58362e662a1b69b51ef0d936e4aff979a18
        name: Cancel Previous Workflow Runs
        with:
          workflow_id: ${{ github.event.workflow.id }}
